export enum Routes {
  FetchCharacters = 'FetchCharacters',
  CreateCharacter = 'CreateCharacter',
  RemoveCharacter = 'RemoveCharacter',
  UpdateCharacter = 'UpdateCharacter',
  CreateCharacterExtra = 'CreateCharacterExtra',
  RemoveCharacterExtra = 'RemoveCharacterExtra',
  FetchChapters = 'FetchChapters',
  CreateChapter = 'CreateChapter',
  UpdateChapter = 'UpdateChapter',
  RemoveChapter = 'RemoveChapter',
  FetchObjects = 'FetchObjects',
  CreateObject = 'CreateObject',
  RemoveObject = 'RemoveObject',
  UpdateObject = 'UpdateObject',
  FetchGroups = 'FetchGroups',
  CreateObjectExtra = 'CreateObjectExtra',
  RemoveObjectExtra = 'RemoveObjectExtra',
  FetchConfig = 'FetchConfig',
  CreateConfig = 'CreateConfig',
  RemoveConfig = 'CreateConfig',
  ExportChapter = 'ExportChapter',
  CreateGroup = 'CreateGroup',
  UpdateGroup = 'UpdateGroup',
  RemoveGroup = 'RemoveGroup',
  GroupAddChapter = 'GroupAddChapter',
  GroupRemoveChapter = 'GroupRemoveChapter'
}
